# Generated by Django 3.0.5 on 2020-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='billing_details_first_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='billing_details_surname',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pick_up_point',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_reference',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shop_client_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fulfilment_method',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
