# Generated by Django 3.0.5 on 2020-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bol_client_id',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bol_client_secret',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
    ]
