# Generated by Django 3.0.5 on 2020-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_reference',
            field=models.TextField(default=None, null=True),
        ),
    ]
