# Generated by Django 3.0.5 on 2020-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_api', '0002_auto_20200429_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='firstname',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='lastname',
            field=models.TextField(blank=True, default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
