# Generated by Django 3.0.5 on 2020-04-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_api', '0003_auto_20200429_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='lastname',
        ),
    ]
