# Generated by Django 3.0.5 on 2020-04-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='bol_client_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bol_client_secret',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.TextField(default=''),
        ),
    ]
