# Generated by Django 3.0.5 on 2020-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_auto_20200428_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bol_client_id',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='bol_client_secret',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.TextField(default=None),
        ),
    ]
